// rex/cmd/rexc/main.go

package main

import (
	"flag"
	"fmt"
	"os"

	"rgehrsitz/rex/pkg/compiler"
	"rgehrsitz/rex/pkg/logging"
)

func main() {
	if err := mainFunc(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func mainFunc() error {
	config, err := parseFlags(os.Args[1:])
	if err != nil {
		return fmt.Errorf("failed to parse flags: %w", err)
	}

	if err := run(config); err != nil {
		return fmt.Errorf("application failed: %w", err)
	}

	return nil
}

type Config struct {
	JSONFilePath string
	OutputPath   string
	ValidateOnly bool
	LogLevel     string
	LogOutput    string
}

func parseFlags(args []string) (*Config, error) {
	config := &Config{OutputPath: "output.bytecode"}
	if len(args) > 0 && args[0] == "validate" {
		config.ValidateOnly = true
		args = args[1:]
	}
	fs := flag.NewFlagSet("rexc", flag.ContinueOnError)

	// Customize usage message
	fs.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage of rexc:\n")
		fmt.Fprintf(os.Stderr, "  rexc [flags]\n")
		fmt.Fprintf(os.Stderr, "  rexc validate [flags]\n\n")
		fmt.Fprintf(os.Stderr, "Flags:\n")
		fs.PrintDefaults()
		fmt.Fprintf(os.Stderr, "\nExample:\n")
		fmt.Fprintf(os.Stderr, "  rexc -rules input_rules.json -output rules.bytecode\n")
		fmt.Fprintf(os.Stderr, "  rexc validate -rules input_rules.json\n")
	}

	fs.StringVar(&config.JSONFilePath, "rules", "", "Path to the input JSON file (required)")
	fs.StringVar(&config.OutputPath, "output", config.OutputPath, "Path to the compiled bytecode file")
	fs.StringVar(&config.LogLevel, "loglevel", "info", "Set log level: panic, fatal, error, warn, info, debug, trace")
	fs.StringVar(&config.LogOutput, "logoutput", "console", "Set log output: console or file")

	err := fs.Parse(args)
	if err != nil {
		return nil, fmt.Errorf("failed to parse flags: %w", err)
	}

	if config.JSONFilePath == "" {
		fs.Usage()
		return nil, fmt.Errorf("input JSON file path is required (use -rules flag)")
	}

	return config, nil
}

func run(config *Config) error {
	return runWithGenerator(config, compiler.GenerateBytecode)
}

func runWithGenerator(config *Config, generateBytecode func(*compiler.Ruleset) (compiler.BytecodeFile, error)) error {
	if err := logging.ConfigureLogger(config.LogLevel, config.LogOutput); err != nil {
		return fmt.Errorf("failed to configure logger: %w", err)
	}

	jsonData, err := readJSONFile(config.JSONFilePath)
	if err != nil {
		return fmt.Errorf("failed to read JSON file: %w", err)
	}

	ruleset, err := compiler.Parse(jsonData)
	if err != nil {
		return fmt.Errorf("failed to parse JSON file %q: %w", config.JSONFilePath, err)
	}

	if config.ValidateOnly {
		fmt.Printf("Ruleset %q is valid\n", config.JSONFilePath)
		return nil
	}

	bytecodeFile, err := generateBytecode(ruleset)
	if err != nil {
		return fmt.Errorf("failed to generate bytecode: %w", err)
	}

	fmt.Println("Generated Bytecode:")

	if err := compiler.WriteBytecodeToFile(config.OutputPath, bytecodeFile); err != nil {
		return fmt.Errorf("failed to write bytecode to file: %w", err)
	}

	fmt.Printf("Successfully generated bytecode and wrote to %q\n", config.OutputPath)
	return nil
}

func readJSONFile(filepath string) ([]byte, error) {
	return os.ReadFile(filepath)
}
